### ISSUE TITLE
HTMLのinputからの値取得について

### ISSUE THREAD

**Issue by Keigo01** [MaxfieldWalker/neumann#12]
optionの各種表示ができたので、値取得をしようと思ったのですが、CoffeeScriptでの取得方法が見当たらなかったので、jQueryで書きましたが、ボタンを押した時点で”Uncaught TypeError: view[methodName] is not a function”エラーを吐きました。これ以外の方法、またはこのエラーの解決方法をご存知の方は教えてください。
![issue](https://cloud.githubusercontent.com/assets/20119916/16898610/f2a30854-4c1a-11e6-9994-cf2368ff3270.PNG)

**Comment by maxfie1d** [comment]
ソースは画像じゃなくて文字として貼ってね(´；ω；｀)コピペしたい時とかあるので．
**```coffeescript**と**```**でソースを囲うとできます．こんな感じで．

``` coffeescript
console.log 'hello'
```

ここから本題

``` coffeescript
($) ->
```

のところは何をやりたいのか不明だけどjquery使うなら

``` coffeescript
$ = require 'jquery'
```

それと要素の取得だけど，$('#memberPriority')で直接取得はたぶんできないから，一番親要素にoutletつけて

``` coffeescript
@div outlet: 'container', =>

-----------

@container.find('#memberPriority')
# もしくは
@container.get(0).find('#memberPriority')
```

あたりでできると思います．

**Comment by Keigo01** [comment]
`$ = require 'jquery' 
-----
@div class: 'option-editor', outlet: 'container', =>
-----
　@form =>
        @input type: "button", value: "Application", id: 'appButton', click: 'hoge'

　hoge: =>
	console.log "#{@container.get(0).find('#memberPriority')}"`

の修正を加えて実行すると、同様に”Uncaught TypeError: view[methodName] is not a function”を吐きました。この修正でおかしなとことかありますか。hogeはdiv直下のインデントにあります。

**Comment by Keigo01** [comment]
’’’coffeescript hoge'''

**Comment by Keigo01** [comment]
`hoge`

**Comment by Keigo01** [comment]
`$ = require 'jquery'`
`------`
`@div class: 'option-editor', outlet: 'container', =>`
`-----`
``

**Comment by Keigo01** [comment]
"'coffeescript
hoge
"'

**Comment by Keigo01** [comment]
'''h'''

**Comment by Keigo01** [comment]
'''
$ = require 'jquery'
-----
@div class: 'option-editor', outlet: 'container', =>
-----
	@form =>
		@input type: "button", value: "Application", id: 'appButton', click: 'hoge'

	hoge: ->
		console.log @container.find('#memberPriority')
'''
と修正を施したのですが、以前”Uncaught TypeError: view[methodName] is not a function”がでます。
hogeの位置はdiv直下です。インデントがおかしいのかと、何種類か試しましたが、divの下では同じエラーが出て、divの外では、”Uncaught TypeError: Cannot read property 'find' of undefined"を吐きました。
質問してばかりで申し訳ないのですが、解決策ご存知でしたらお願いします。

**Comment by Keigo01** [comment]
'''coffeescript
$ = require 'jquery'
-----
@div class: 'option-editor', outlet: 'container', =>
-----
	@form =>
		@input type: "button", value: "Application", id: 'appButton', click: 'hoge'

	hoge: ->
		console.log @container.find('#memberPriority')
'''
と修正を施したのですが、以前”Uncaught TypeError: view[methodName] is not a function”がでます。
hogeの位置はdiv直下です。インデントがおかしいのかと、何種類か試しましたが、divの下では同じエラーが出て、divの外では、”Uncaught TypeError: Cannot read property 'find' of undefined"を吐きました。
質問してばかりで申し訳ないのですが、解決策ご存知でしたらお願いします。

**Comment by Keigo01** [comment]
```coffeescript
console.log 'hoge'
```

**Comment by Keigo01** [comment]
``` coffeescript
$ = require 'jquery'
------
@div class: 'option-editor', outlet: 'container', =>
------
@form =>
        @input type: "button", value: "Application", id: 'appButton', click: 'hoge'

hoge: ->
    console.log @container.find('#memberPriority')
```

と修正を加えたのですが、依然同じエラーを吐きます。hogeはdiv直下です。インデントも一通り試しましたが改善されませんでした。質問ばかりで申し訳ないんですが、解決策ご存知でしたらお願いします。

**Comment by maxfie1d** [comment]
うーん抜粋だけだと判断できないから一度今の状態でpushして見せてください。

**Comment by maxfie1d** [comment]
64dffeb でちょっと動くようにしました．

`hoge`メソッドのインデントが右にずれていたのがまずかったです．
それとクリックなどのイベントの購読は`initialize`の中で書くようです．

``` coffeescript
initialize: ->
    @appButton.on 'click', => @hoge()
```

**Comment by maxfie1d** [comment]
動くようになったのでcloseします．
