### ISSUE TITLE
EditHistoryRuleで最近のコードほど点数が低い

### ISSUE THREAD

**Issue by maxfie1d** [MaxfieldWalker/neumann#13]
`lib/algorithm/neumann-algorithm.coffee`でグラフを表示した結果ですが，
新しいものほど点数が低く，古いものほど点数が高くなってる気がするのですが，
これであってるんだっけ

![image](https://cloud.githubusercontent.com/assets/7913793/16906585/f5562754-4cf4-11e6-8a8d-a55dbaaaa5ec.png)

**Comment by miwamot** [comment]
確認しました。
僕のミスで
「最終変更時間からどのくらい古いのか」

``` coffeescript
timeMilliSecond = maxTime - codeLine.timestamp.getTime()
```

と
「作成開始時（初commit時間からの経過時間」

``` coffeescript
timeMillsecond =  codeLine.timestamp.getTime() - minTime
```

を混同したせいで
MaxfieldWalkerさんの言うとおり、古いものほど点数が高くなっていました。

`b2ce98a`で修正を行いました。ただ優先度の関係なのか、EditHisottyRuleのみが適用されたコード同士では新しいコードの方が高い点数になっていますが、他のruleが入るとちょっと良くわからないです。

念のため確認お願いします。
ていうか優先度の変更ってどこで効いたっけ。。

**Comment by maxfie1d** [comment]
修正確認しました．いいと思います(たぶん)

> ていうか優先度の変更ってどこで効いたっけ。。

他の話題は新しいIssueで⤴
