### ISSUE TITLE
グーグル先生がおもしろいことやってた

### ISSUE THREAD

**Issue by maxfie1d** [MaxfieldWalker/neumann#14]
なにやら面白いページを見つけました。

> より高頻度にバグを修正し、かつ最近になって集中的に直しているほど、スコアが大きくなる。
> そしてスコアが大きいほど、相対的に見てそのコードにはバグがある可能性が高い、というのがこのアルゴリズムの意味になります。

[グーグルのバグ予測アルゴリズムを実装したツール「bugspots」について](http://qiita.com/okappy/items/e5fc62f9026e0d73c3e9)

**Comment by tarohi24** [comment]
bugspotsはファイル単位なので少しアプローチは違いますが、コミットログからfixを取ってくるアプローチとこのサイトでのScoresは流用できそうですね
