### ISSUE TITLE
suspiciousnessReasonが動作しない

### ISSUE THREAD

**Issue by tarohi24** [MaxfieldWalker/neumann#15]
自分で産んだバグなのですが...
Consoleでは

```
TypeError: Cannot read property 'evaluationReason' of undefined
    at NeumannAlgorithm.module.exports.NeumannAlgorithm.evaluationReason (/Users/wataru/neumann/lib/algorithm/neumann-algorithm.coffee:77:23)
```

となっています。対処法が分かり次第fixしますが、とりあえず既知のバグ報告ということで挙げておきます。

**Comment by maxfie1d** [comment]
金曜までに(できれば金曜日になる前に)直せそう？

**Comment by maxfie1d** [comment]
とりあえず

``` coffeescript
class MidnightRule extends RuleBase
    @RuleNum = Rules.Midnight
    constructor: (@start, @end) ->
```

じゃなくて

``` coffeescript
class MidnightRule extends RuleBase
    constructor: (@start, @end) ->
        @RuleNum = Rules.Midnight
```

こう．プロパティはコンストラクタの内側に書く

**Comment by tarohi24** [comment]
後のことを考えるとRulesクラス群はインスタンス化されて使われるとは限らないのでconstructorの中に書くのはあまり良いとは思えないのですが、プロパティを外側に書いた場合のデメリット等はありますか? (ネットで探してみた感じコンストラクタ外で使用されている例も結構見かけるのですが)

**Comment by tarohi24** [comment]
期日については原因がわからないのでなんとも言えないです‥
もし当日デモをするならgit resetして使っていただく方が良いかもしれません..

**Comment by tarohi24** [comment]
すいません、どうやら調べてみるとCoffeeScriptではコンストラクタの位置づけが違うみたいですね。直してpushします。

**Comment by tarohi24** [comment]
何度もお騒がせして申し訳ありません。
fixしました。
https://github.com/MaxfieldWalker/neumann/commit/86a5edb636573312d48a428806df9b33f5e94a13
