### ISSUE TITLE
[TODO] GitHub APIからの情報の取得

### ISSUE THREAD

**Issue by tarohi24** [MaxfieldWalker/neumann#16]
[GitHub API](https://developer.github.com/v3/)を使えばユーザーのタイムゾーンなどの情報が得られるので、
- 時差の問題...タイムゾーンを得ることで解消
- Suspicious Member... GitHubのユーザー情報で、Contribute数が多いほど経験がある<=>信頼できると判定

としたら既存の問題のいくつかが解決できそうなのですがいかがでしょうか。

**Comment by maxfie1d** [comment]
GitHubとの連携は大いに結構だと思います．是非やりましょう．
APIを使うにあたって，この辺りのライブラリが使えそうです．
- [https://github.com/michael/github](https://github.com/michael/github)
- [https://github.com/mikedeboer/node-github](https://github.com/mikedeboer/node-github)
