### ISSUE TITLE
Unreliable memberをGithubのユーザー名で指定したい

### ISSUE THREAD

**Issue by tarohi24** [MaxfieldWalker/neumann#17]
現状はgit blameからユーザー名を取得してくるので、そのユーザーのローカル名でunreliable membersを指定する形になっていますが、これがGithubのユーザー名で指定できると便利だと思います。

**Comment by maxfie1d** [comment]
ちょっと調べてみたけど，GitHubのユーザー名とコミットのAuthorやCommitterを結びつけるものがなさげだった。GitHubにコミットしたらたとえば僕だったらWeb上ではMaxfieldWalkerさんと表示されるけどgitのログに残ってる実際のコミット著者はNaoto Ishidaみたいな。gitのコマンドを使って得られる情報からGitHubのユーザーを特定する方法はあるのだろうか。メールアドレスが一致したら(名前が違っても)同一人物と判定するとか？？

**Comment by tarohi24** [comment]
現実的にはメールアドレスかな
