### ISSUE TITLE
ユーザーごとの時差を登録する設定がほしい

### ISSUE THREAD

**Issue by tarohi24** [MaxfieldWalker/neumann#18]
#17 にも絡んでくる話ですが、settings画面でユーザーごとの個別設定(時差、reliable or not)などを設定する画面があればいいと思います。(あとあとAPIを使って情報を自動取得するにせよ、ユーザーごとに設定する、というクラスは必要になってくると思うので)

**Comment by maxfie1d** [comment]
Atomの設定画面はリアルタイムに作れない(パッケージが読み込まれた時点で決定する)感じなのと，ユーザーごとに設定となるとUIがまどろっこしくなるような気がするので，`user-settings.json`を作ってそこに書いてもらうみたいな感じにするといいかも。atom-beautifyは`.jsbeautifyrc`ファイルにJSON形式で設定を書くことができるので参考になりそう。JSONを読み込んで処理する部分は463行目あたりから。
(https://github.com/Glavin001/atom-beautify/blob/6a99b0a1bd675d1be904fa19aa3f39bc2a5564af/src/beautifiers/index.coffee)
