### ISSUE TITLE
Macでgit blameが表示されない

### ISSUE THREAD

**Issue by tarohi24** [MaxfieldWalker/neumann#2]
Ctrl+Gの直後にCtrl+Bを試してみたのですがblameが表示されませんでした。
メニューバーからPackage→neuman→git blameを選択しても同様に表示されないのでMacではまだ正しく動作しないのだと思います。
対策法が見当たり次第コミットします。

**Comment by maxfie1d** [comment]
まじですか(´；ω；｀)
ちなみにWindowsだとこんな感じに表示されます．
とりあえずこの問題は保留にしときます...

![image](https://cloud.githubusercontent.com/assets/7913793/16009693/d90b9e3c-31b8-11e6-93f5-9a685ebbe679.png)

**Comment by tarohi24** [comment]
2912137f898a2471253e3f4cc6aa6bcb79d23402 にてMacでも動作することを確認しました。

**Comment by maxfie1d** [comment]
わーい！
