### ISSUE TITLE
時差の扱いについて

### ISSUE THREAD

**Issue by maxfie1d** [MaxfieldWalker/neumann#8]
タイムゾーンの異なる外国の方のコミットの時差を考慮していないため，MidnightRuleにおいて正しく夜に書かれたコードかどうか判定出来ない場合があります．

どう対処しましょうか

**Comment by tarohi24** [comment]
ユーザー情報はgitではなくgithubでの情報なので(しかもhubコマンドでは取得できない) 自動で時差を考慮するのは難しいと思います。
現状としてはUnreliableMembersの情報にタイムゾーンのフィールドを追加するのが現実的かもしれません。
