### ISSUE TITLE
バージョン1.0.0公開に向けて

### ISSUE THREAD

**Issue by maxfie1d** [MaxfieldWalker/neumann#9]
7/22(金)の発表前にneumannをバージョン1.0.0として公開したいと思います．つきましては
- 動作確認
- コメントを追加(5人以外が読んでも理解できるように分かりやすく)
- 不要になったコードを削除する
- イースターエッグをしこむ

など，neumannをよりよくするために各自最終調整を行ってください．

**Comment by tarohi24** [comment]
READMEを英語で書くならコメントも英語にしたほうがいいですし、コメントを日本語にするならメインターゲットは日本語ユーザーなのでREADMEも日本語で書いたほうがいいと思います。(README_ENみたいなものを用意して英語版を他に用意するみたいなのはありだと思います)
現状からの移行コストを考えると、他にも実装すべきことはあるので日本語で運用すべきだと思いますがどうでしょうか。

**Comment by maxfie1d** [comment]
コメントが日本語なのはちょっと思ってた．
開発者は日本人でも利用者は日本人以外もいていいからREADMEは英語でもいいかなとかっこつけて英語で書いてみました(´；ω；｀)READMEの日本語版用意しときます．

**Comment by maxfie1d** [comment]
バージョン1.0.0公開したのでcloseします．
